@echo off
setlocal
echo =======================================================
echo Starting Next.js + Tailwind scaffold setup...
echo =======================================================

echo [1/5] Creating package.json...
echo {> package.json
echo   "name": "nextjs-app-template",>> package.json
echo   "version": "0.1.0",>> package.json
echo   "private": true,>> package.json
echo   "scripts": {>> package.json
echo     "dev": "next dev",>> package.json
echo     "build": "next build",>> package.json
echo     "start": "next start",>> package.json
echo     "lint": "next lint">> package.json
echo   },>> package.json
echo   "dependencies": {>> package.json
echo     "next": "15.1.0",>> package.json
echo     "react": "19.0.0",>> package.json
echo     "react-dom": "19.0.0">> package.json
echo   },>> package.json
echo   "devDependencies": {>> package.json
echo     "@types/node": "^20",>> package.json
echo     "@types/react": "19.0.1",>> package.json
echo     "@types/react-dom": "19.0.1",>> package.json
echo     "typescript": "^5",>> package.json
echo     "tailwindcss": "^3.4.1",>> package.json
echo     "postcss": "^8",>> package.json
echo     "autoprefixer": "^10.4.16",>> package.json
echo     "eslint": "^9",>> package.json
echo     "eslint-config-next": "15.1.0">> package.json
echo   }>> package.json
echo }>> package.json

echo [2/5] Creating tsconfig.json...
echo {> tsconfig.json
echo   "compilerOptions": {>> tsconfig.json
echo     "target": "ES2017",>> tsconfig.json
echo     "lib": ["dom", "dom.iterable", "esnext"],>> tsconfig.json
echo     "allowJs": true,>> tsconfig.json
echo     "skipLibCheck": true,>> tsconfig.json
echo     "strict": true,>> tsconfig.json
echo     "noEmit": true,>> tsconfig.json
echo     "esModuleInterop": true,>> tsconfig.json
echo     "module": "esnext",>> tsconfig.json
echo     "moduleResolution": "bundler",>> tsconfig.json
echo     "resolveJsonModule": true,>> tsconfig.json
echo     "isolatedModules": true,>> tsconfig.json
echo     "jsx": "preserve",>> tsconfig.json
echo     "incremental": true,>> tsconfig.json
echo     "plugins": [{ "name": "next" }],>> tsconfig.json
echo     "paths": { "@/*": ["./src/*"] }>> tsconfig.json
echo   },>> tsconfig.json
echo   "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],>> tsconfig.json
echo   "exclude": ["node_modules"]>> tsconfig.json
echo }>> tsconfig.json

echo [3/5] Creating Tailwind and PostCSS configurations...
echo import type { Config } from "tailwindcss";> tailwind.config.ts
echo const config: Config = {>> tailwind.config.ts
echo   content: ["./src/pages/**/*.{js,ts,jsx,tsx,mdx}","./src/components/**/*.{js,ts,jsx,tsx,mdx}","./src/app/**/*.{js,ts,jsx,tsx,mdx}"],>> tailwind.config.ts
echo   theme: { extend: { colors: { background: "var(--background)", foreground: "var(--foreground)" } } },>> tailwind.config.ts
echo   plugins: [],>> tailwind.config.ts
echo };>> tailwind.config.ts
echo export default config;>> tailwind.config.ts

echo module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } }> postcss.config.js

echo [4/5] Creating basic source files...
if not exist src\app mkdir src\app

echo @tailwind base;> src\app\globals.css
echo @tailwind components;>> src\app\globals.css
echo @tailwind utilities;>> src\app\globals.css
echo :root { --background: #ffffff; --foreground: #171717; }>> src\app\globals.css
echo @media (prefers-color-scheme: dark) { :root { --background: #0a0a0a; --foreground: #ededed; } }>> src\app\globals.css
echo body { color: var(--foreground); background: var(--background); font-family: Arial, Helvetica, sans-serif; }>> src\app\globals.css

echo import './globals.css'> src\app\layout.tsx
echo export const metadata = { title: 'Create Next App', description: 'Generated by create next app' }>> src\app\layout.tsx
echo export default function RootLayout({ children }: { children: React.ReactNode }) { return ( ^<html lang="en"^>^<body^>{children}^</body^>^</html^> ) }>> src\app\layout.tsx

echo export default function Home() { return ( ^<main className="flex min-h-screen flex-col items-center justify-center p-24"^>^<h1 className="text-4xl font-bold"^>Next.js Template^</h1^>^</main^> ) }> src\app\page.tsx

echo [5/5] Installing npm packages (No audit, no fund)...
call npm install --no-audit --no-fund

echo =======================================================
echo Setup complete! Run 'npm run dev' to start the server.
echo =======================================================
endlocal
